apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-boilerplate-app
  labels:
   app: go-boilerplate-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-boilerplate-app
  template:
    metadata:
      labels:
        app: go-boilerplate-app
    spec:
      containers:
      - name: go-boilerplate-app
        image: maartendesnouck/go-boilerplate-app:firsttry
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: regcred
