apiVersion: v1
kind: Service
metadata:
  name: go-boilerplate-app
  labels:
    app: go-boilerplate-app
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 8080
  selector:
    app: go-boilerplate-app
